using System;
using System.IO;
using IdSharp.AudioInfo;
using NUnit.Framework;

namespace IdSharp.AudioInfo.Tests.Format
{
    [TestFixture]
    internal static class FlacTests
    {
        private static readonly string FlacTestFilePath = Path.Combine(TestContext.CurrentContext.TestDirectory, "TestData", "sample.flac");
        private static readonly string NonExistentPath = Path.Combine(TestContext.CurrentContext.TestDirectory, "TestData", "does_not_exist.flac");

        [Test]
        public static void Construct_ReadsFlacFile_Successfully()
        {
            Assert.That(File.Exists(FlacTestFilePath), Is.True, "sample.flac fixture not found");
            var flac = new Flac(FlacTestFilePath);
            Assert.Multiple(() =>
            {
                Assert.That(flac.Frequency, Is.GreaterThan(0));
                Assert.That(flac.Channels, Is.GreaterThan(0));
                Assert.That(flac.Samples, Is.GreaterThan(0));
                Assert.That(flac.TotalSeconds, Is.GreaterThan(0));
                Assert.That(flac.Bitrate, Is.GreaterThan(0));
            });
        }

        [Test]
        public static void FileType_IsFlac()
        {
            Assume.That(File.Exists(FlacTestFilePath), Is.True);
            var flac = new Flac(FlacTestFilePath);
            Assert.That(flac.FileType, Is.EqualTo(AudioFileType.Flac));
        }

        [Test]
        public static void Frequency_IsExpectedValue_ForKnownFixture()
        {
            Assume.That(File.Exists(FlacTestFilePath), Is.True);
            var flac = new Flac(FlacTestFilePath);
            // The sample was generated by ffmpeg sine wave at 440Hz, default sample rate is 44100
            Assert.That(flac.Frequency, Is.EqualTo(44100));
        }

        [Test]
        public static void Construct_ThrowsFileNotFoundException_ForNonExistentFile()
        {
            Assert.That(File.Exists(NonExistentPath), Is.False);
            // Flac only catches InvalidDataException, so FileNotFoundException propagates
            _ = Assert.Throws<FileNotFoundException>(() => _ = new Flac(NonExistentPath));
        }

        [Test]
        public static void Construct_ThrowsInvalidDataException_ForMp3File()
        {
            var mp3Path = Path.Combine(TestContext.CurrentContext.TestDirectory, "TestData", "file_example_MP3_700KB.mp3");
            Assume.That(File.Exists(mp3Path), Is.True);
            // MP3 file doesn't start with "fLaC" marker
            _ = Assert.Throws<InvalidDataException>(() => _ = new Flac(mp3Path));
        }
    }
}
