using System;
using System.IO;
using IdSharp.AudioInfo;
using NUnit.Framework;

namespace IdSharp.AudioInfo.Tests.Format
{
    [TestFixture]
    internal static class RiffWaveTests
    {
        private static readonly string WavTestFilePath = Path.Combine(TestContext.CurrentContext.TestDirectory, "TestData", "sample.wav");
        private static readonly string NonExistentPath = Path.Combine(TestContext.CurrentContext.TestDirectory, "TestData", "does_not_exist.wav");

        [Test]
        public static void Construct_ReadsWavFile_Successfully()
        {
            Assert.That(File.Exists(WavTestFilePath), Is.True, "sample.wav fixture not found");
            var wav = new RiffWave(WavTestFilePath);
            Assert.Multiple(() =>
            {
                Assert.That(wav.Frequency, Is.GreaterThan(0));
                Assert.That(wav.Channels, Is.GreaterThan(0));
                Assert.That(wav.TotalSeconds, Is.GreaterThan(0));
                Assert.That(wav.Bitrate, Is.GreaterThan(0));
            });
        }

        [Test]
        public static void FileType_IsRiffWave()
        {
            Assume.That(File.Exists(WavTestFilePath), Is.True);
            var wav = new RiffWave(WavTestFilePath);
            Assert.That(wav.FileType, Is.EqualTo(AudioFileType.RiffWave));
        }

        [Test]
        public static void Frequency_IsExpectedValue_ForKnownFixture()
        {
            Assume.That(File.Exists(WavTestFilePath), Is.True);
            var wav = new RiffWave(WavTestFilePath);
            Assert.That(wav.Frequency, Is.EqualTo(44100));
        }

        [Test]
        public static void Channels_IsExpectedValue_ForKnownFixture()
        {
            Assume.That(File.Exists(WavTestFilePath), Is.True);
            var wav = new RiffWave(WavTestFilePath);
            // The sample was generated by ffmpeg sine wave, default is mono
            Assert.That(wav.Channels, Is.GreaterThan(0));
        }

        [Test]
        public static void AudioDataOffset_IsPositive()
        {
            Assume.That(File.Exists(WavTestFilePath), Is.True);
            var wav = new RiffWave(WavTestFilePath);
            Assert.That(wav.AudioDataOffset, Is.GreaterThan(0));
        }

        [Test]
        public static void Construct_ThrowsInvalidDataException_ForMp3File()
        {
            var mp3Path = Path.Combine(TestContext.CurrentContext.TestDirectory, "TestData", "file_example_MP3_700KB.mp3");
            Assume.That(File.Exists(mp3Path), Is.True);
            // MP3 file doesn't start with "RIFF"
            _ = Assert.Throws<InvalidDataException>(() => _ = new RiffWave(mp3Path));
        }

        [Test]
        public static void Construct_ThrowsFileNotFoundException_ForNonExistentFile()
        {
            Assert.That(File.Exists(NonExistentPath), Is.False);
            _ = Assert.Throws<FileNotFoundException>(() => _ = new RiffWave(NonExistentPath));
        }
    }
}
